choiSite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('choiStory.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

choiStory/urls.py
from django.urls import path
from . import views
from . views import post_detail

app_name = 'choiStory'
urlpatterns = [
    path('', views.main, name='main'),
    path('resume/', views.aboutMe, name='resume'),
    path('myProjects/', views.myProjects, name='myProjects'),
    path('contactMe/', views.contactMe, name='contactMe'),
    path('post/<int:id>/', post_detail, name="post_detail"),
]

choiStory/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class blog(models.Model):

	title = models.CharField(max_length=50)
	preview = models.TextField(max_length=50)
	content = RichTextField() #content = models.TextField(max_length=1000)
	posted = models.DateTimeField(auto_now_add=True)

	def __str__(self):
	    return self.title

choiStory/views.py
from django.shortcuts import get_object_or_404, render
from .models import blog
from django.http import HttpResponse
from django.http import Http404
from django.template import loader
from django.core.mail import send_mail

# Create your views here.
def main(request):
    return render(request, 'choiStory/main.html')

def aboutMe(request):
    return render(request, 'choiStory/aboutMe.html')

def myProjects(request):
    posts = blog.objects.all()
    return render(request, 'choiStory/myProjects.html', {'posts': posts})

def contactMe(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        subject = request.POST.get("subject")
        msg = request.POST.get("msg")
        data = {
            "Name" : name ,
            "E-MAIL" : email,
            "Subject" : subject,
            "Message" : msg
        }
        message = '''
        New message: {}
        
        From: {}
        '''.format(data["Message"], data["E-MAIL"])
        send_mail(data["Subject"], message, '', ["kk6962289@gmail.com"])
        return HttpResponse('Your message has been sent. Thank you.')

    return render(request, 'choiStory/contactMe.html', {})

# def contactMe(request):
#     return render(request, 'choiStory/contactMe.html')

def post_detail(request, id):
	post = get_object_or_404(blog, id=id)
	return render(request, 'choiStory/post_detail.html', {"post": post})

choiStory/templates/choiStory/HeaderAndMenu.html
<header>
    <div class="banner">
        <br />
        <h1>YEONJONG CHOI</h1>
        <hr style="height:1px;margin:auto;border-width:0;width:15%;color:black;background-color:black">
        <br />
        <div id = 'personalInfo'>
            <h6><span class="material-icons-outlined">phone_android</span> +1 (647) 460-8761</h6>
            <h6><span class="material-icons-outlined">email</span> cpalove3@gmail.com</h6>
        </div>
        <br />
    </div>
</header>
<div class="topnav" id = 'topMenu'>
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'main' %}nav-link active{% endif %}" id="home" href="/"> HOME </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'resume' %}nav-link active{% endif %}" href="{% url 'choiStory:resume' %}">RESUME</a>
        </li>
        <li class="nav-item">
            <a id = "mp" class="nav-link {% if request.resolver_match.url_name == 'myProjects'%}
            nav-link active{% endif %}" href="{% url 'choiStory:myProjects' %}">MY PROJECTS</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'contactMe'%}nav-link active{% endif %}" href="{% url 'choiStory:contactMe' %}">CONTACT ME</a>
        </li>
    </ul>
</div>

<script>

</script>

choiStory/templates/choiStory/aboutMe.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
    <title>YEONJONG CHOI</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <style>
        #pdfMain{
            text-align: center;
            width: 100%;
            height: 100%;
        }
    </style>
</head>
<body>
<!----------------------------------------------
- {% static 'files/onReceiveTRdata.pdf' %}
----------------------------------------------->
    <div class="container">
        {% include 'choiStory/HeaderAndMenu.html' %}
        <section class="content">
            <main id = "pdfMain">
                <iframe src="{% static 'files/resume.pdf' %}" width="100%" height="1000px">
                </iframe>
            </main>
        </section>
        <footer>
            <small>&copy; Copyright 2022, Yeonjong Choi</small>
        </footer>
    </div>

</body>
</html>

choiStory/templates/choiStory/contactMe.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
    <title>YEONJONG CHOI</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <style>
        .contactForm{
            font-family: Times New Roman;
            padding-top: 30px;
            padding-bottom: 30px;
            margin: auto;
            margin-top: 30px;
            margin-bottom: 30px;
            border-width: 1px 1px 1px 1px;
            border-color: black;
            border-style: solid;
            border-radius: 25px;
            display: inline-block;
            justify-content: left;
            text-align: left;
        }
        .halfLeftCf{
            margin-top: 20px;
            margin-left:5%;
            float: left;
        }
        .halfRightCf{
            margin-top: 20px;
            margin-right:5%;
            float: right;
        }
        #input-name{
            border-width: 0px 0px 1px 0px;
            border-color: black;
            border-style: solid;
        }
        #input-email{
            border-width: 0px 0px 1px 0px;
            border-color: black;
            border-style: solid;
        }
        #input-subject{
            border-width: 0px 0px 1px 0px;
            border-color: black;
            border-style: solid;
        }
        #input-submit{
            width:50%;
            margin-top: 20px;
            margin-left:25%;
            margin-right:25%;
        }
        #form{
            position:relative;
            width: 550px;
            margin:auto;
        }
        textarea{
            overflow:hidden;
            height: 150px;
            width:250px;
            font-size:12px;
            margin: auto;
            display:block;
            border-radius:10px;
            border:2px solid #556677;
        }
    </style>
</head>
<body>
    <div class="container">
        {% include 'choiStory/HeaderAndMenu.html' %}
        <section class="content" id="contentContactMe">
            <main class = "contactForm">
                <div id = "form">
                    <h1>Contact Me</h1>
<!--                    <form class="cf" action="https://formsubmit.co/kk6962289@gmail.com" method="POST">-->
                    <form class="cf" action="" method="POST">
                      {% csrf_token %}
                      <div class="halfLeftCf">
                        <input type="text" id="input-name" name="name" placeholder="Name" required> </br></br>
                        <input type="email" id="input-email" name="email" placeholder="Email Address" required></br></br>
                        <input type="text" id="input-subject" name="subject" placeholder="Subject" required></br></br>
                      </div>
                      <div class="halfRightCf">
                        <textarea name="message" type="text" id="input-message" name="msg" placeholder="Message" required></textarea>
                      </div>
                      <input type="submit" value="Submit" class="btn btn-outline-secondary" id="input-submit">
                    </form>
                </div>
            </main>
        </section>
        <footer>
            <small>&copy; Copyright 2022, Yeonjong Choi</small>
        </footer>
    </div>

</body>
</html>

choiStory/templates/choiStory/main.html
<!----------------------------------------------
- cd C:\Users\cpalo\myEnv\Scripts\choiSite
- python manage.py runserver
- https://realpolarbearking.github.io/choiSite/
- URL: polarbearking.pythonanywhere.com
----------------------------------------------->

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
    <title>YEONJONG CHOI</title>
    <style>
        #choiMain{
            font-family: Times New Roman;
            font-size: 20px;
            margin: auto;
            margin-top: 100px;
            margin-bottom: 100px;
            text-align: center;
        }
        .introBox {
            position: relative;
            align-items: center;
            margin: auto;
            border: 1px solid #bbb;
        }

        .introBox :after {
            display: block;
            content: "";
            width: 20px;
            height: 20px;
            position: absolute;
            top: -5px;
            right: -5px;
            border-top: 3px solid black;
            border-right: 3px solid black;
        }

        .introBox :before {
            display: block;
            content: "";
            width: 20px;
            height: 20px;
            position: absolute;
            bottom: -5px;
            left: -5px;
            border-bottom: 3px solid black;
            border-left: 3px solid black;
        }
        .introContent{
             margin-top: 25px;
             margin-bottom: 25px;
             margin-left: 50px;
             margin-right: 50px;
        }
    </style>
</head>
<body>
    <div class="container">
        {% include 'choiStory/HeaderAndMenu.html' %}
        <section class="content">
            <main id = "choiMain">
                <div class="introBox">
                    <div class="introContent">
                    Hello, I'm <b>YEONJONG CHOI</b>!</br>
                    Welcome to my website!</br>
                    I am a recent graduate from <u>York Unviersity, Toronto ON, CA</u>.
                    </div>
                </div>
            </main>
        </section>
        <footer>
            <small>&copy; Copyright 2022, Yeonjong Choi</small>
        </footer>
    </div>

</body>
</html>

choiStory/templates/choiStory/myProjects.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
    <title>YEONJONG CHOI</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <style>
        #projectMain{
            font-family: Times New Roman;
            text-align: center;
            margin: auto;
            margin-top: 30px;
            margin-bottom: 30px;
        }
        .card-title{
            font-weight: bold;
            font-size: 20px;
        }
        .card-preview{
            font-size: 15px;
        }
    </style>
</head>
<body>
    <div class="container">
        {% include 'choiStory/HeaderAndMenu.html' %}
        <section class="content">
            <main id = "projectMain">
                  <div class="projectHeader">
                     <h1 class="center-align">Projects</h1>
                  </div>
                  <div class="projectContainer">
                     <div class="row">
                        {% for post in posts %}
                        <div class="col s12 m4">
                           <div class="card" style="width: 18rem; margin-top: 40px;">
                                  <div class="card-body">
                                     <span class="card-title">	{{ post.title }}</span>
                                     <p class="card-preview">{{ post.preview }}</p>
                                     <div class="card-action">
                                        <a class="btn btn-primary stretched-link" href="/post/{{ post.id }}">Read More</a>
                                     </div>
                                  </div>
                              </div>
                           </div>
                        {% endfor %}
                        </div>
                  </div>
            </main>
        </section>
        <footer>
            <small>&copy; Copyright 2022, Yeonjong Choi</small>
        </footer>
    </div>
</body>
</html>

choiStory/templates/choiStory/post_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
    <title>YEONJONG CHOI</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <style>
        #projectMain{
            font-family: Times New Roman;
            margin: auto;
            margin-top: 30px;
            margin-bottom: 30px;
        }
        .center-align{
            text-align: center;
        }
        .card-title{
            font-weight: bold;
            font-size: 20px;
        }
        .card-preview{
            font-size: 15px;
        }
    </style>
</head>
<body>
    <div class="container">
        {% include 'choiStory/HeaderAndMenu.html'%}
        <section class="content">
            <main id = "projectMain">
                  <div class="projectContainer">
                      <div class="container">
                         <h1 class="center-align">{{ post.title }}</h1>
                      </div>
                      <div class="container">
                         <div class="row">
                            <div class="col s12 m12">
                               <p class = "center-align">{{ post.preview }}</p>
                               <br>
                               <hr>
                               <p>{{ post.content|safe }}</p>
                            </div>
                         </div>
                      </div>
                  </div>
            </main>
        </section>
        <footer>
            <small>&copy; Copyright 2022, Yeonjong Choi</small>
        </footer>
    </div>
</body>
</html>